version: 0.2

phases:
#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 368888336862.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
#      - docker login -u haffman44 -p pvg@tgn6kxn-ytv*XJB
      - echo Build started on `date`
      - cd frontend
      - npm install
      - find src/ -type f -exec sed -i 's/localhost:3001/student-demo-lecture-ecs-lb-1-450180631.us-east-1.elb.amazonaws.com/g' {} +
      - npm run build
#      - docker build -t todo-fe:latest .
#      - docker logout
  post_build:
    commands:
      - echo Build completed on `date`
#      - echo Logging in to Amazon ECR...
#      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 368888336862.dkr.ecr.us-east-1.amazonaws.com
#      - echo Pushing the Docker image...
#      - docker tag todo-fe:latest 368888336862.dkr.ecr.us-east-1.amazonaws.com/todo-fe-repo:latest
#      - docker push 368888336862.dkr.ecr.us-east-1.amazonaws.com/todo-fe-repo:latest
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
#  discard-paths: yes