version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd frontend
      - npm install
      - find src/ -type f -exec sed -i 's/todo-be-ecs-lb-3-539608311.us-east-1.elb.amazonaws.com/student-demo-lecture-ecs-lb-1-450180631.us-east-1.elb.amazonaws.com/g' {} +
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
